# SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause
# Copyright 2024 Hewlett Packard Enterprise Development LP
#
# Makefile for CXI (Cassini) InfiniBand device driver.
#

obj-$(CONFIG_INFINIBAND_CXI) += cxi_ib.o

cxi_ib-y := cxi_com_cmd.o cxi_com.o cxi_main.o cxi_verbs.o
